# Generated by Django 2.2.1 on 2019-05-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arr',
            fields=[
                ('arrx', models.FloatField()),
                ('arry', models.FloatField()),
                ('arrz', models.FloatField()),
                ('time', models.CharField(max_length=50)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'arr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Datatable',
            fields=[
                ('dip', models.IntegerField()),
                ('temp', models.IntegerField()),
                ('humi', models.IntegerField()),
                ('mq', models.SmallIntegerField()),
                ('qual', models.IntegerField()),
                ('time', models.CharField(max_length=50)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'datatable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dht11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.CharField(max_length=10)),
                ('humi', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'dht11',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('age', models.IntegerField()),
            ],
            options={
                'db_table': 'user1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank='True', max_length=32)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
    ]
